build:
  test: 
    image: uafgina/chefdk:0.12.0
    commands:
      - eval "$(chef shell-init sh)"
      - rake
  upload:
    image: uafgina/chefdk:0.12.0
    commands:
      - eval "$(chef shell-init sh)"
      - berks install
      - berks upload
    when:
      event: [push]
      branch: master
