name 'sample-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sample-cookbook'
long_description 'Installs/Configures sample-cookbook'
version '2.0.0'
